"""Increase password_hash and api_key field lengths

Revision ID: 21206b7e8daa
Revises: 8c1f845a0577
Create Date: 2025-03-28 12:32:07.885625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21206b7e8daa'
down_revision = '8c1f845a0577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('api_key',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.drop_constraint('users_api_key_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('users_api_key_key', ['api_key'])
        batch_op.alter_column('api_key',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
